name: Build Unity Android
on: workflow_dispatch

jobs:
  build:
    name: Build for Android 🎮
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # These lines "force-feed" the paths to Unity 2018
          ANDROID_SDK_ROOT: /opt/android-sdk-linux
          ANDROID_HOME: /opt/android-sdk-linux
          ANDROID_NDK_ROOT: /opt/android-sdk-linux/ndk-bundle
        with:
          targetPlatform: Android
          unityVersion: 2018.2.21f1
          # This specific image is known to have the SDK at /opt/
          customImage: 'unityci/editor:ubuntu-2018.2.21f1-android-0'
          projectPath: .
          # This line tells the builder to use the paths we just defined
          unityBuilderOptions: '-androidSdkRoot /opt/android-sdk-linux -androidNdkRoot /opt/android-sdk-linux/ndk-bundle'
