name: Build Unity Android
on: workflow_dispatch

jobs:
  build:
    name: Build for Android 🎮
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          # 2019 is the "sweet spot" for legacy builds on GitHub Actions
          unityVersion: 2019.4.40f1
          # This forces it to ignore minor version mismatches
          versioning: Semantic

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: COMZ-Android-Build
          path: build/Android
