name: Build Unity Android
on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build for Android 🎮
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: COMZ-Android-Build
          path: build/Android
